### ISSUE TITLE
refresh_token table should not be dependent on user_profile

### ISSUE THREAD

**Issue by auahmed** [networknt/light-oauth2#117]
when creating the database, the refresh_token table is dependent on user-profile user id:
````
FOREIGN KEY (user_id) REFERENCES user_profile(user_id),
````
this causes an issue to create token when LDAP has been used for authentication

**Comment by stevehu** [comment]
For some authentication/authorization providers, there is no record in user_profile table and the refresh token shouldn't have any dependency on the user_profile. For example, LDAP authentication/authorization.  We need to break the dependency on user service and user_profile table so that we can make user service optional.
